### ISSUE TITLE
integrated yt-dlp update 

### ISSUE THREAD

**Issue by jdeath** [alexta69/metube#109]
Still loving this docker. Way easier for the family.

Would be nice to have a button to upgrade yt-dlp or have option to use a version from a persistent storage location. Seems wasteful to pull a new image just for a yt-dlp update. Going into the container and doing a `pip install --upgrade yt-dlp` works fine, but not persistent.

**Comment by alexta69** [comment]
Glad to hear you like it!

I'm really surprised though! The MeTube image is ~70 MB. I assume you're not on dialup, if you're using MeTube.. and on a broadband connection, downloading 70 MB should not take more than a dozen seconds, it's really quite a small download. If you use a tool like [Watchtower](https://github.com/containrrr/watchtower) to do it automatically for you, you don't even need to wait that, you just wake up to a fresh MeTube instance whenever there's an update. On the other hand, implementing what you're suggesting will complicate MeTube quite a bit. Frankly I really don't see the justification for that, unless there's a use case here that I'm not seeing...

Let me know what you think.

**Comment by jdeath** [comment]
Thanks for the thoughtful reply. I just thought it would be easier to keep up to date in case you take break. For instance, latest metube I just pulled (maybe I did it wrong) doesn't have the latest yt-dlp. I think that will update more than your code.

I can just edit the entry point to do a pip install on container start.

**Comment by alexta69** [comment]
I understand why the problem popped up then. There's a nightly automatic job that pulls the latest yt-dlp and publishes a new docker image if there's been an update. So the process doesn't depend on me :) The thing is, in the last few days the build didn't pass because there was a problem, and the version of yt-dlp lagged behind the latest, and that's when you happened to look at it and see it was out of date... I've fixed the build today, and hopefully it will keep running smoothly.

Pip install on container start won't work out of the box because the container normally runs with non-root permissions, and pip won't be able to overwrite the library. It can be reshuffled and reworked, but I really don't think it's worth the effort and the added complexity...

**Comment by jdeath** [comment]
Got it. Thanks.

**Comment by MortRainey** [comment]
But how to upgrade yt-dlp on local installations?

**Comment by PikuZheng** [comment]
> But how to upgrade yt-dlp on local installations?

```
 python -m pip install --upgrade yt-dlp
```
