### ISSUE TITLE
If you download two videos with the same name, only the first video will be downloaded.

### ISSUE THREAD

**Issue by MrZomka** [alexta69/metube#139]
Hello, I'm running MeTube in a Docker container and have recently experienced this issue. Has anybody have a fix for it? Thanks :)

**Comment by PikuZheng** [comment]
This problem occurs in the case of non-youtube videos. #124 
Can you give a sample link?

**Comment by MadKillerChicken** [comment]
Kinda late to the party, have solve a similar issue I had, maybe it helps someone else down the road.
Issue turned out to be the default value of OUTPUT_TEMPLATE, `%(title)s.%(ext)s`.
When downloading several videos with the same title, once the first had been added, all other were skipped due to being considered duplicates, as they all had the same filename.
The solution was changing the value to: `%(title)s [%(id)s].%(ext)s`, which causes the video id to be added to the filename.
