### ISSUE TITLE
Option to download MP3

### ISSUE THREAD

**Issue by Dogepot2** [alexta69/metube#18]
It would be great to have the ability to download just audio, or change/add the presets for download

**Comment by alexta69** [comment]
Hi @Dogepot2 ,
A preset for audio-only is an interesting idea. I'm not sure about the ability to configure, as that would require persistent configuration storage, something that I've been avoiding so far (since it makes metube easier to deploy, and there's no pressing need for it).
I'm closing this issue for now, but if you feel like adding the audio-only preset, feel free to implement it and open a PR, I'll be glad to merge it.
Thanks
Alex

**Comment by alexta69** [comment]
Hey again @Dogepot2 ,
I pushed an option for an audio-only download now.
I hope you find it useful!
Cheers
