### ISSUE TITLE
anyway to change the base image to alpine:edge

### ISSUE THREAD

**Issue by PikuZheng** [alexta69/metube#182]
Considering that alpine with python has a smaller image than python:slim, is there a way to change the base image to alpine:edge? 

In addition, alpine:edge uses ffmpeg 5.1.1 by default to avoid problems caused by 5.0

**Comment by PikuZheng** [comment]
#173

**Comment by alexta69** [comment]
We're not using python:slim, we're using python:alpine, so we're on the smaller image already. We could move to alpine base instead of python, but I'm a bit wary of the edge, I don't want breakages to occur.. The next alpine release will happen in November, which is already pretty close. And then it will have the latest ffmpeg. Perhaps we can live with that
