### ISSUE TITLE
db error file does not exist

### ISSUE THREAD

**Issue by doubleespresso2018** [alexta69/metube#199]
Currently running into this error where the db file doesn't exist.  Can't add to links to download.

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "app/main.py", line 97, in delete
    status = await (dqueue.cancel(ids) if where == 'queue' else dqueue.clear(ids))
  File "/app/app/ytdl.py", line 286, in cancel
    self.queue.delete(id)
  File "/app/app/ytdl.py", line 180, in delete
    with shelve.open(self.path, 'w') as shelf:
  File "/usr/local/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.8/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

**Comment by AntaresEight** [comment]
Maybe this will help you or someone else with a similar issue. I did not have the exact same `dbm.error: db file doesn't exist;` that you have, but after searching I ran across this issue and it helped me rethink my troubleshooting and ultimately led me to fixing it. 

Is your download directory and state directory _local_ or is it on a SMB or NFS share? You may want to verify permissions and recreate the `.metube` directory manually as a test. I suggest trying a local download and state directory with wide open permissions to rule out any file creation or permission issues. Stop the container, delete the `.metube` directory and any files within it (should have `queue` and `completed` files in there), restart the container, see if the `.metube` directory and files are created. If they are created are the permissions correct? If not, try creating the `.metube` directory manually with full permissions, etc.

The `.metube` directory I'm referring to will be created in `/path/to/downloads/` while the container is starting up. Sample Run command from the instructions: 
```
docker run -d -p 8081:8081 -v /path/to/downloads:/downloads alexta69/metube
```
## More Rambling Details About My Error
My downloads folder is setup on a NFS share and hasn't had any issues until recently. I'm not sure if a TrueNAS update did this to me or if I did it to myself. I most likely created the issue myself. Anyway, after being confused for a bit I eventually unmounted the NFS share and restarted the docker container. When I did that the `.metube` directory and files `queue` and `completed` were created properly on the local machine (since NFS was unmounted but the metube container was still using the same directory). I then stopped the container, removed the `.metube` directory, modified NFS settings on the server and restarted the NFS service, re-mounted the NFS share, and started the metube docker container again. It then worked properly.

Details about the paragraph above
My NFS share is mounted to `/mnt/nfs-metube-downloads`. When I unmount NFS and restart the container it still uses the `/mnt/nfs-metube-downloads` directory but it's just the local filesystem at that point and things seem to work.
The command I used to create the container:
```shell
docker run -d -p 8081:8081 -v /mnt/nfs-metube-downloads:/downloads --user 1001:1001 --restart unless-stopped --name metube alexta69/metube
```

The confusing part of my issue was the `.metube` directory and `queue` file was being created, although `queue` was 0 bytes. The `completed` file was not being created. There were no file creation errors or file permission errors in the log file that obviously pointed to the issue (i.e. `docker logs metube`).

My `docker logs metube` error is shown below:
```shell
Setting umask to 022
Creating download directory /downloads and state directory /downloads/.metube
User set by docker; running MeTube as 1001:1001
Traceback (most recent call last):
  File "app/main.py", line 75, in <module>
    dqueue = DownloadQueue(config, Notifier())
  File "/app/app/ytdl.py", line 195, in __init__
    self.queue = PersistentQueue(self.config.STATE_DIR + '/queue')
  File "/app/app/ytdl.py", line 150, in __init__
    with shelve.open(path, 'c'):
  File "/usr/local/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.8/dbm/__init__.py", line 89, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

**Comment by alexta69** [comment]
Closing (please reopen if it's still an issue)
