### ISSUE TITLE
Add support for pornhubpremium.com

### ISSUE THREAD

**Issue by jansengorilla** [alexta69/metube#208]
Shouldn't be too difficult. When manually removing /premium/ from the copied url (thus pointing to pornhub.com, rest of the link unchanged) download works fine. Automation would be great 😁

**Comment by alexta69** [comment]
As mentioned [here](https://github.com/alexta69/metube#troubleshooting-and-submitting-issues), MeTube is only a GUI for [yt-dlp](https://github.com/yt-dlp/yt-dlp). Before opening issues here, please try downloading your videos using yt-dlp directly. If it doesn't work, please open an issue for the yt-dlp project. If it works with yt-dlp but doesn't work with MeTube, please reopen the issue here with logs of what you're seeing.
