### ISSUE TITLE
autoupdate for youtube-dl

### ISSUE THREAD

**Issue by Rpsl** [alexta69/metube#22]
because that service can work at long time (i use that on my nas and have several month of uptime) youtube-dl package can be outdated.
also we have locked version of package in [Pipfile.lock](https://github.com/alexta69/metube/blob/master/Pipfile.lock#L216)

I think we should think of userstory for autoupdate youtube-dl in docker image or some different workaround

what do you think about that?

**Comment by alexta69** [comment]
Hi @Rpsl ,
Yes, I also thought it's needed, but never got around to implementing it.. I do upgrade dependencies and push them to master here once in a while, so if you have an auto-updater for your docker containers (such as watchtower or ouroboros), you should have a fairly recent version. But since it's a critical dependency because it sometimes breaks (youtube change their interface), it's worth having auto-update inside MeTube. I'm not sure when I'll get around to it myself. If you feel like implementing it, I'll gladly merge it in..
Cheers
Alex

**Comment by Rpsl** [comment]
I have several solution but not sure them good in terms of clean code:
1) Not use youtube-dl as python package. If use it as independent application we can run `youtube-dl -U` by cron
2) Use download manager as independent part of application. Then we can doing stop and update by master process
3) Use self update before start application and add optional param for self stop by timer. `Start by docker -> timer -> Stop by application -> Auto start by docker -> Self update`

I think the right solution is to use youtube-dl as an application. I'm not sure if we can get the progress status of the download then, do you know?

**Comment by fejich** [comment]
This method is good

**Comment by alexta69** [comment]
The scheduled job has been implemented, and has already updated youtube-dl last night. So the image is going to be auto-updated from now on every time a new version of youtube-dl becomes available.
