### ISSUE TITLE
Password protect metube UI

### ISSUE THREAD

**Issue by suntong** [alexta69/metube#308]
Same asking as #163, 

> Is there any way to apply auth (username and password) in metube Web UI??

I know the given answer is,

> Use "username" and "password" parameters in YTDL_OPTIONS (https://github.com/alexta69/metube#configuration-via-environment-variables).

However, I'm not sure if it is for **youtube-dl** username and password or the username and password for the **metube Web UI** instead? I tried to ask the question there several times in different ways, but no any reply, hence asking again as a new question. Thanks @alexta69.

**Comment by PikuZheng** [comment]
I don't think so. "username" and "password" in YTDL_OPTIONS are used for "authentication purposes" <sup>[1](https://github.com/yt-dlp/yt-dlp/blob/db7b054a6111ca387220d0eb87bf342f9c130eb8/yt_dlp/YoutubeDL.py#L194C33-L194C61)</sup>  <sup>[2](https://github.com/alexta69/metube/issues/226)</sup>

I think a better way is to use a reverse proxy such as nginx #150 #217 #226

**Comment by suntong** [comment]
Yeah, agree. Thanks for the confirmation and links!

**Comment by PikuZheng** [comment]
> I think that's good enough for me as well. Can you elaborate a bit how do you do it please?

set  docker env "URL_PREFIX" to something https://github.com/alexta69/metube#configuration-via-environment-variables

If you need to return 404 when opening the root path (instead of jumping to URL_PREFIX), delete lines 162 to 164 https://github.com/alexta69/metube/blob/8950665f0662d51ef092fc450b3b34ac50316bbf/app/main.py#L162
