### ISSUE TITLE
Request: hit-counter

### ISSUE THREAD

**Issue by hungntv** [alexta69/metube#320]
Can you add hit-counter function like https://hits.seeyoufarm.com/

Thanks

**Comment by PikuZheng** [comment]
I don't understand. Do you want to check the clicks of this github project?

**Comment by PikuZheng** [comment]
Since obtaining github container image downloads requires authorization (not public data), it will be a huge challenge. Additionally, this cannot include quantities that are self-compiled using source code
On the other hand, counting installations requires each terminal to connect to a private statistics server, which is not feasible for installation privacy.
