### ISSUE TITLE
Include FFMPEG to automatically convert to desired codec

### ISSUE THREAD

**Issue by jamess60** [alexta69/metube#423]
When downloading youtube videos as MP4, they come down as Googles VP9 codec + OPUS audio which isn't super compatible (EG works with VLC but not Quicktime). Ideally, id choose H264 (or 5) + AAC audio. 

Would it be possible to include FFMPEG in the container and have an option to download+covert? 

Failing that (as that may be complex to implement), could we at least have the resolution appended to the filename so its easier to work with in Handbrake?

**Comment by PikuZheng** [comment]
metube includes ffmpeg, however this is a known issue of ffmpeg.

**Comment by PikuZheng** [comment]
However, there are several possible ways to solve this problem.
One is to change the metube base image from alpine to ubuntu in order to use the [latest and modified ffmpeg](https://github.com/yt-dlp/FFmpeg-Builds/releases/latest).
Another way is to downgrade ffmpeg to 6.0. Version 6.0 can process the video correctly, but the processed video may not be recognized by some players.
And another way is to set YTDL_OPTIONS `"format_sort":["codec:avc:m4a"]` to completely avoid using vp9 (which is my choice).

**Comment by jamess60** [comment]
Tried adding ``` - YTDL_OPTIONS='"format_sort":["codec:avc:m4a"]'``` to my compose and I get "YTDL_OPTIONS is invalid" in the log output. 

Tried looking unto the tags and cant see the Ubuntu image you mentioned - do you know the tag? https://github.com/alexta69/metube/pkgs/container/metube/202861299?tag=2024-04-12

**Comment by jamess60** [comment]
Thanks! This worked:

```
        environment:
            - 'YTDL_OPTIONS={"format_sort":["codec:avc:m4a"]}'
```

**Comment by gerroon** [comment]
Do I need a custom dockert image to use ?
```
    environment:
            - 'YTDL_OPTIONS={"format_sort":["codec:avc:m4a"]}'
```
