### ISSUE TITLE
Is it possible to add user login and authentication mechanism before submitting the download request?

### ISSUE THREAD

**Issue by rowidalex** [alexta69/metube#43]
Hello, it is possible to add a user login and authentication mechanism before submitting the download request?
The use case here is that I'd like to publish the metube app via swag to the Internet, but without user authentication, the attacker could flood the system once they discovered the metube page.
One reference example is theAria2 WebUI. It needs a credential code to authenticate and submit the request.
Thanks a lot.

**Comment by alexta69** [comment]
Hi,
The linuxserver/swag image comes with an authentication solution that is generic, and works with everything you put behind it -- I think this is the right way to approach it, instead of having every application implement its own authentication logic, which I think is a big waste. Check out this post for instructions for configuring it:
https://www.linuxserver.io/blog/2020-08-26-setting-up-authelia
This is how I also configured it in my own setup.. and I can attest it works great :)
