### ISSUE TITLE
Add a "Best [mp4+m4a]" option

### ISSUE THREAD

**Issue by ksarnelli** [alexta69/metube#49]
Lately "Best" has been downloading vp9+opus codecs for all of the Youtube videos I've downloaded, but I prefer avc1/aac .  I've gotten around this by overriding the format using YTDL_OPTIONS (i'm using docker) with the following: `{"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best"}`

It would be great if an option was added to the dropdown to force the mp4+m4a option. Thanks.

**Comment by alexta69** [comment]
Yes, I changed that because it seems that the highest resolutions are often only available in non-mp4 formats.

The UI work for adding such an option would be somewhat complex. I don't want to duplicate all the entries in the dropdown with mp4 variants (it'll be a mess), so it has to be a separate option (a checkbox or something like that), so there needs to be a place for it. And once this checkbox is added, it'd make sense to save its value, and managing saved preferences is something metube doesn't do at all at the moment, it'll require big changes.

Maybe another option would be to add a dedicated environment variable for it (FORCE_MP4 or something like that). The question is whether people have this preference for all the videos they download, or is it important to allow selecting it per download. What is your use case, in this regard?

**Comment by jdeath** [comment]
2nd this for custom profiles. Audio only was downloading as webm for me, so I added this custom docker, but then always does m4a and wont download videos
```
`YTDL_OPTIONS: '{"format": "bestaudio/best","postprocessors": [{"key": "FFmpegExtractAudio","preferredcodec": "m4a","preferredquality": "192"}]}'`
```

**Comment by alexta69** [comment]
Actually changing the audio mode to always force m4a makes sense, I doubt anyone is looking to download audio webm files. This is an easy change in the code. Question is, how we make this selectable for video as well.

**Comment by ksarnelli** [comment]
> Yes, I changed that because it seems that the highest resolutions are often only available in non-mp4 formats.
> 
> The UI work for adding such an option would be somewhat complex. I don't want to duplicate all the entries in the dropdown with mp4 variants (it'll be a mess), so it has to be a separate option (a checkbox or something like that), so there needs to be a place for it. And once this checkbox is added, it'd make sense to save its value, and managing saved preferences is something metube doesn't do at all at the moment, it'll require big changes.
> 
> Maybe another option would be to add a dedicated environment variable for it (FORCE_MP4 or something like that). The question is whether people have this preference for all the videos they download, or is it important to allow selecting it per download. What is your use case, in this regard?

My use case is really just to prevent transcoding when playing on devices that only don't support vp9 natively.  Also, many times the original source uploaded to youtube is an MP4 (avc1/aac) and the vp9/opus are transcodes of the original (although at a smaller file size).

**Comment by alexta69** [comment]
Which would be better for you -- an env. variable FORCE_MP4 that you can set, and it will always be in force, or allow selecting it in the UI via a checkbox, but then you'd have to select it every time?
Actually, in the UI we can save it in a cookie so it'll be persistent in the browser.

**Comment by ksarnelli** [comment]
A checkbox in the UI with the state saved in a cookie would be great!

**Comment by alexta69** [comment]
Done. Let me know how well it works for you.
