### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno -2] Name does not resolve>

### ISSUE THREAD

**Issue by jeremytodd1** [alexta69/metube#51]
I just installed this onto my Unraid server and when I try to download youtube videos it'll look like it's doing it correctly, but a ways into the download it'll error out with this error:

- ERROR: unable to download video data: <urlopen error [Errno -2] Name does not resolve>

For reference, I was testing out MeTube with this youtube video url: https://www.youtube.com/watch?v=kKB1L9ATm2Q
It does happen with any youtube link I've given it so far though.

**Comment by alexta69** [comment]
I've tested it with my copy of MeTube and it downloads fine. It must be something with your environment, with your DNS settings or something like that. To debug this, I would try a few things -- first, exec a shell inside the metube docker and run the yt-dlp command there to try to download the video. Assuming the docker container is named "metube":
```
# docker exec -ti metube sh
# yt-dlp https://www.youtube.com/watch?v=kKB1L9ATm2Q
```
That should give the same error. Then try downloading the yt-dlp command on the host and running it there, outside the docker, to see if the docker is the problem. I'd start there...
I'm closing the issue since it doesn't look like there's a problem with metube in this case.
